import type { Metadata } from "next";
import { inter, crimsonText, robotoMono, poppins, nunito } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${crimsonText.variable} ${robotoMono.variable} ${poppins.variable} ${nunito.variable}`}>
      <body className="antialiased font-body">
        {children}
      </body>
    </html>
  );
}
